// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import {
  appendSslModeIfNeeded,
  databaseUrlNeedsSsl,
} from "./src/prisma/database-url.util";

/** CLI Prisma : SSL seulement pour connexions externes (pas URL interne Render). */
function resolveDatabaseUrl(): string | undefined {
  const raw = process.env["DATABASE_URL"];
  if (!raw) return undefined;

  if (databaseUrlNeedsSsl(raw)) {
    process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
  }
  return appendSslModeIfNeeded(raw);
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx ts-node prisma/seed.ts",
  },
  datasource: {
    url: resolveDatabaseUrl(),
  },
});
